server:
  port: 8080
  servlet:
    contextPath: /api/exchangeRates
  max-http-request-header-size: 16KB

spring:
  application:
    name: exchange-rates
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: admin
      password: password
      roles: USER

exchange:
  api:
    url: ${EXCHANGE_RATES_API_URL:https://v6.exchangerate-api.com/v6}
    key: ${EXCHANGE_RATES_API_KEY:95f68d812c4e2eca7dd8509b}

logging:
  level:
    root: INFO
